/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/upload": {
    /** Test upload */
    post: operations["upload"];
  };
}

export interface components {
  schemas: {
    UploadResult: {
      /**
       * Format: int64
       * @example 10
       */
      id?: number;
    };
  };
}

export interface operations {
  /** Test upload */
  upload: {
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["UploadResult"];
        };
      };
      401: {
        content: {
          "application/json": { foo: string; bar: boolean };
        };
      };
      405: {
        content: {
          "application/json": { baz: string; boo: boolean };
        };
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          orderId: number;
          userId: number;
          /** Format: binary */
          file: Blob;
        };
      };
    };
  };
}

export interface external {}
